project_id = "oqwxhhdqxzigxcysoufa"

[functions.send-booking-email]
verify_jwt = false

[functions.send-studio-email]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
